### ISSUE TITLE
Permissions issues running on WSL 2

### ISSUE THREAD

**Issue by djmccarthy12** [fkie-cad/cwe_checker#139]
I have a Debian box running on WSL2 and I have gotten Ghidra and Rust installed without issue. However when running CWE checker, I run into the following permissions issue:

`thread 'main' panicked at 'called Result::unwrap() on an Err value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', caller/src/main.rs:262:10
stack backtrace:
   0:     0x563b08fc1ef0 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x563b08fc1ef0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b08fc1ef0 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563b08fc1ef0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563b08fe776c - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x563b08fbe3a2 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x563b08fc4465 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563b08fc4465 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563b08fc4465 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x563b08fc4108 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x563b08fc4c01 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x563b08fc4747 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
  12:     0x563b08fc23ac - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563b08fc46a9 - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x563b08fe5921 - core::panicking::panic_fmt::ha0bb065d9a260792
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:     0x563b08fe5743 - core::option::expect_none_failed::h7e1dd0a94971eb61
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
  16:     0x563b08e5d99d - cwe_checker::run_with_ghidra::hefc12dba33663939
  17:     0x563b08e5b1e8 - cwe_checker::main::h16e80103ba1c8ae3
  18:     0x563b08e4d283 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf02e4990abdd83b7
  19:     0x563b08e4d299 - std::rt::lang_start::{{closure}}::hb83bf57cf898bc11
  20:     0x563b08fc5027 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  21:     0x563b08fc5027 - std::panicking::try::do_call::h81cbbe0c3b30a28e
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  22:     0x563b08fc5027 - std::panicking::try::hbeeb95b4e1f0a876
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  23:     0x563b08fc5027 - std::panic::catch_unwind::h59c48ccb40a0bf20
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  24:     0x563b08fc5027 - std::rt::lang_start_internal::ha53ab63f88fee728
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  25:     0x563b08e5e662 - main
  26:     0x7f6a3f4cc09b - __libc_start_main
  27:     0x563b08e1e0aa - _start
  28:                0x0 - <unknown>`

Trying to figure out where exactly it is running into a permissions issue, but this being my first time working with Rust, the trace is a bit cryptic. Any assistance would be greatly appreciated!

**Comment by Enkelmann** [comment]
The exact line in the code where it runs into the issue is in `caller/src/main.rs:262`. What happens is that the cwe_checker runs Ghidra as a child process and then tries to access its output. This fails with the error message `Os { code: 13, kind: PermissionDenied, message: "Permission denied" }` and cwe_checker crashes in return. So it seems that the execution of Ghidra failed because of permission issues. Maybe the cwe_checker process has no rights to access or execute programs in the folder where Ghidra is installed?

But it is definitely a bug on the cwe_checker side that this error message is not nicely formatted for human consumption. I will update the code accordingly!

**Comment by djmccarthy12** [comment]
That appears to have been the issue, changed permissions recursively on the Ghidra install folder and it's working properly. Much appreciated!
