### ISSUE TITLE
busybox binary still getting error.

### ISSUE THREAD

**Issue by anzosasuke** [fkie-cad/cwe_checker#169]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/cwe_checker_lib/src/analysis/graph.rs:312:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Enkelmann** [comment]
Can you provide the affected binary? None of my busybox samples trigger this bug. And since it is very likely that the root cause of the bug is not where the crash occurs, I probably need a sample to find the root cause.

**Comment by anzosasuke** [comment]
here it is.
[busybox.zip](https://github.com/fkie-cad/cwe_checker/files/6359023/busybox.zip)

**Comment by Enkelmann** [comment]
Thanks! I can confirm the issue, we are working on a fix.

**Comment by Enkelmann** [comment]
Short update: The original bug is fixed thanks to PR #171. But we encountered a second bug afterwards, which we are currently fixing.

**Comment by Enkelmann** [comment]
The second bug is now also fixed thanks to PR #172.

Apparently we still have problems handling the MIPS delay slots in some cases (which results in a lot of log messages for the busybox binary). At the moment we are debating whether we want to make a larger rewrite of the affected code to fix this and similar issues, so I do not know yet when exactly we will tackle this problem. But this is definitely not part of the original issue here anymore. ;-)
