### ISSUE TITLE
analysis UEFI moduls

### ISSUE THREAD

**Issue by admenURA** [fkie-cad/cwe_checker#175]
Good day
Is it possible to adjust the checker for the analysis of .efi files?
Will changing the header of the .efi files to the ELF format help?

**Comment by Enkelmann** [comment]
I think .efi files are just PE-files (at least the .efi file I tested it on is), which we can already handle. So you shouldn't need to adjust anything for the cwe_checker to work on them.

As a little disclaimer: The support for PE-files is experimental. We do not test everything on PE-files yet, so you may experience more bugs / less analysis quality with them compared to ELF files. And most checks expect the binary to link against libc to work. So I cannot say how useful the cwe_checker is for .efi files right now.
