### ISSUE TITLE
error: Invalid value for '--config <config>'

### ISSUE THREAD

**Issue by sh4m2hwz** [fkie-cad/cwe_checker#191]
$ sudo docker run --rm -v/path/to/binary_file:/path/to fkiecad/cwe_checker /path/to -p=CWE78,CWE134,CWE190,CWE215,CWE243,CWE332,CWE367,CWE426,CWE467,CWE476,CWE560,CWE676,CWE782,Memory -j -q -out=f.json
error: Invalid value for '--config <config>': No such file or directory (os error 2)

**Comment by Enkelmann** [comment]
Your command line does not contain the `--config` parameter, so I assume that you actually used a different command to invoke the cwe_checker. In any case, the error message implies that the configuration file did not exist. Maybe you forgot to mount the configuration file to the docker container?

**Comment by Enkelmann** [comment]
Since there was no further response, I am assuming that the issue is solved. Feel free to reopen the issue if not.
