### ISSUE TITLE
Error("missing field `tid`", line: 23469063, column: 9) while run docker  

### ISSUE THREAD

**Issue by chenjianquan7** [fkie-cad/cwe_checker#219]
run cmd:
docker run --rm -v /root/Desktop/iscm:/input fkiecad/cwe_checker /input
output:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `tid`", line: 23469063, column: 9)', src/caller/src/main.rs:300:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

whats wrong?how to debug ,thank you

**Comment by Enkelmann** [comment]
This is a bug in the cwe_checker (or, more precisely, in the P-Code-Extractor component of the cwe_checker). Can you provide the affected binary? Currently, there is no mechanism included in the cwe_checker to automatically debug these kind of problems, so it will be very difficult for me to identify the cause of the bug without the affected binary.

**Comment by Enkelmann** [comment]
Closing this issue, since I cannot do anything without an example binary to reproduce the bug.
