### ISSUE TITLE
Failed to find pass: cwe-checker

### ISSUE THREAD

**Issue by gorgiaxx** [fkie-cad/cwe_checker#23]
When I run 
```docker run -v "$PWD"/test:/tmp/test fkiecad/cwe_checker_travis_docker_image bap /tmp/test --pass=cwe-checker```

The error shows:
Failed to find pass: cwe-checker

**Comment by Enkelmann** [comment]
You are using the wrong docker image. Try `fkiecad/cwe_checker` instead. 

In `fkiecad/cwe_checker_travis_docker_image` only the dependencies of *cwe_checker* are installed. We use it as a base image when building the docker image through the  `make docker` command.

**Comment by gorgiaxx** [comment]
@Enkelmann I understand. It works now! Thank you.

**Comment by krsh** [comment]
I have the same error, I installed `cwe-checker` with the Ocaml package manager _Opam_.

**Comment by Enkelmann** [comment]
Can you tell me the exact shell command you used? And the version number of the cwe_checker you installed?

**Comment by krsh** [comment]
the command is:

`$ bap abc.bin --pass=cwe-checker --cwe-checker-config=../cwe_config.json`

and cwe_checker version is: 

```
$ opam show  cwe_checker

<><> cwe_checker: information on all versions <><><><><><><><><><><><><><><><><>
name                   cwe_checker
all-installed-versions 0.3 [system]
all-versions           0.2  0.3

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       0.3
repository    default
url.src:      "https://github.com/fkie-cad/cwe_checker/archive/v0.3.tar.gz"
url.checksum:
          "md5=fc1ae520b8865426b4c00d319889a639"
          "sha512=4d2d7f81e782baf462b47a3f12b8c5c639338bf29f7555bb9696cf7b4699d89a175351861c75b77c1b76621cd1f1fc03650da3bad493638b6de03d20c4426282"
homepage:     "https://github.com/fkie-cad/cwe_checker"
bug-reports:  "https://github.com/fkie-cad/cwe_checker/issues"
dev-repo:     "git+https://github.com/fkie-cad/cwe_checker"
authors:      "Thomas Barabosch <thomas.barabosch@fkie.fraunhofer.de>"
              "Nils-Edvin Enkelmann <nils-edvin.enkelmann@fkie.fraunhofer.de>"
maintainer:   "CWE_checker Team <nils-edvin.enkelmann@fkie.fraunhofer.de>"
license:      "LGPL-3.0"
depends:      "ocaml" {>= "4.05"}
              "dune" {>= "1.6"}
              "yojson" {>= "1.6.0"}
              "bap" {>= "1.6" & < "2.0"}
              "alcotest" {>= "0.8.3"}
              "core_kernel" {>= "v0.11" & < "v0.12"}
              "ppx_jane" {>= "v0.11" & < "v0.12"}
              "ppx_deriving_yojson" {>= "3.5.1"}
              "odoc" {>= "1.4"}
conflicts:    "fkie-cad-cwe-checker" {!= "0.2"}
synopsis      BAP plugin collection to detect common bug classes
description   cwe_checker is a suite of tools to detect common bug classes such as use of
              dangerous functions and simple integer overflows. These bug classes are formally
              known as Common Weakness Enumerations (CWEs).

```

**Comment by Enkelmann** [comment]
Hmm, everything looks fine there... Ok, possible error causes I can think of:

- You have more than one instance of BAP installed. Either by having more than one switch in Opam or by also having some Linux distribution-specific package of BAP installed. This could cause the call to BAP to not execute the instance installed in the same switch as the cwe_checker but the other installed version (which does not have the cwe_checker registered as a plugin).
- Something weird that could be solved by reinstalling BAP and the cwe_checker?

I will try to reproduce this on my machine over the weekend, but it doesn't look like a bug that I have encountered before. What distribution do you use?

**Comment by krsh** [comment]
I reinstalled Ocaml, Opam, BAP and cwe_checker and now I get:

```
$ bap /usr/bin/lscpu --pass=cwe-checker --cwe-checker-config=../cwe_config.json 
Pass `cwe-checker' failed at runtime with [CWE476] parameters not as expected
Backtrace:
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "src/checkers/cwe_476.ml", line 281, characters 11-57
Called from file "list.ml", line 85, characters 12-15
Called from file "src/main.ml", line 142, characters 12-35
Called from file "lib/bap/bap_project.ml", line 493, characters 56-59
Called from file "lib/bap/bap_project.ml", line 477, characters 20-32
Re-raised at file "lib/bap/bap_project.ml", line 482, characters 6-15
Called from file "lib/bap/bap_project.ml", line 518, characters 4-20
Called from file "lib/bap/bap_project.ml", line 529, characters 10-24
```

I use Ubuntu 18.04.

**Comment by Enkelmann** [comment]
This admittedly unhelpful error message indicates that parameter parsing for the maximum number of steps for the CWE 476 check failed. Try to copy-paste the parameter values from the standard config file and then just change the numbers to the desired values.

Note that the check has been heavily reworked since v0.3, so make sure to use the config file of v0.3 and not the one from the master branch as a blueprint for your config file.

**Comment by krsh** [comment]
I removed the line
```
"strict_memory_policy=false",
```
from the config file, and now it works fine. 
Thanks for your support.
