### ISSUE TITLE
thread 'main' panicked at 'Could not read configuration file

### ISSUE THREAD

**Issue by chenchampion** [fkie-cad/cwe_checker#230]
Hello Sir,

Intalled cwe_checker locally on my macbook,  the tool failed to analyze the binary file.
run command:
cwe_checker bin/ls  #ls is getton from Ubuntu 
or "cwe_checker -c src/config.json bin/ls"
fail info:
thread 'main' panicked at 'Could not read configuration file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/cwe_checker_lib/src/utils/mod.rs:18:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

could you help to check the problem. thank you.

**Comment by Enkelmann** [comment]
This is a known issue (see #142). In short, the configuration file and some other files are copied into the wrong folder during installation on MacOS. You can look at [this comment](https://github.com/fkie-cad/cwe_checker/issues/141#issuecomment-774124750) on how to fix it by hand.

Right now the only fully supported OS is Linux, so you may run into other quirks that I don't know of yet if you use a local installation on MacOS. If you are only interested in running the cwe_checker without modifying its source code, I recommend using the Docker image instead, which should work on any OS.

**Comment by chenchampion** [comment]
thank you. it's very helpful.
