### ISSUE TITLE
Binaries that cause failure

### ISSUE THREAD

**Issue by AndrewJohnson150** [fkie-cad/cwe_checker#247]
Hello,

I've attached some binaries in a zip file that, when analyzed with cwe_checker, cause a failure for some reason or another. These binaries are taken from a Kali Linux 2021.2 image. I disassembled each file in Ghidra to ensure that wasn't causing an issue. I will go through the output of cwe_checker for each file below.

[Here are the binaries.](https://github.com/fkie-cad/cwe_checker/files/7435627/FailToRun.zip)

**tigerdeep**
```
docker run --rm -v C:\Users\Andrew\Repositories\FailToRun\tigerdeep:/input fkiecad/cwe_checker:stable /input
thread 'main' panicked at 'Error while generating runtime memory image: type is too big (1879047925) for 244128', src/caller/src/main.rs:122:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**xfwm4**
```
docker run --rm -v C:\Users\Andrew\Repositories\FailToRun\xfwm4:/input fkiecad/cwe_checker:stable /input
thread 'main' panicked at 'Error while generating runtime memory image: Malformed entity: Section 0 size (0) + offset (4294967296) is out of bounds. Overflowed: false', src/caller/src/main.rs:122:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**cherrytree**

I am not an expert in Ghidra or disassembly in general, but I don't get any error popups when I disassemble this binary in Ghidra. I do see occurrences of 'Error [Bad Instruction]', which could certainly be an issue.
```
docker run --rm -v C:\Users\Andrew\Repositories\FailToRun\cherrytree:/input fkiecad/cwe_checker:stable /input
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/cwe_checker_lib/src/pcode/expressions.rs:31:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**tmux**
 There are occurrences of 'Error [Bad Instruction]' when disassembling this binary as well.
```
docker run --rm -v C:\Users\Andrew\Repositories\FailToRun\tmux:/input fkiecad/cwe_checker:stable /input
thread 'main' panicked at 'Error while generating runtime memory image: Malformed entity: Section 0 size (1039382085632) + offset (1) is out of bounds. Overflowed: false', src/caller/src/main.rs:122:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Bash**
I encounter an error when importing this file into Ghidra which is almost certainly why cwe_checker fails to run. I know this isn't an issue in cwe_checker so there is no need to worry about this, but I've included this file because I have no idea why this would be the case and would appreciate any thoughts on why it might be happening.
```
PS C:\Users\Andrew\Repositories\FailToRun> docker run --rm -v C:\Users\Andrew\Repositories\FailToRun\bash:/input fkiecad/cwe_checker:stable /input
Execution of Ghidra plugin failed: Process was terminated.
ERROR REPORT: Import failed for file: /input (HeadlessAnalyzer)
```

**btrfs-image**
This binary also fails to be analyzed in Ghidra due to a '/ by zero' issue. Again, I know this isn't an issue with cwe_checker, but I would appreciate any ideas on why it would happen.
```
docker run --rm -v C:\Users\Andrew\Repositories\FailToRun\btrfs-image:/input fkiecad/cwe_checker:stable /input
thread 'main' panicked at 'Error while generating runtime memory image: Malformed entity: Section 0 size (1693539964551168) + offset (1129576398848) is out of bounds. Overflowed: false', src/caller/src/main.rs:122:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Enkelmann** [comment]
The bug uncovered by the cherrytree binary was fixed in PR #251. For the other binaries the failures are either due to malformed ELF files (which at least for the near future are out-of-scope for the cwe_checker) or the bug in question is not contained in the cwe_checker itself (the bash binary), I am closing the issue. Feel free to reopen if I overlooked some cwe_checker-specific problem!
