### ISSUE TITLE
How to analyze bare-metal binaries using docker?

### ISSUE THREAD

**Issue by firmianay** [fkie-cad/cwe_checker#254]
Hi,
1. Maybe it's because the stm32f407vg.json path is wrong, how to set the path?
2. Is it possible to analyze .hex files?

```
➜  ~ docker run --rm -v ~/test_sample.bin:/input fkiecad/cwe_checker --bare-metal-config /cwe_checker/bare_metal/stm32f407vg.json /input
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/caller/src/main.rs:115:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Enkelmann** [comment]
Regarding 1:  The example bare-metal config JSON is not contained in the docker container. So you have to mount it into the docker container like the input binary itself. E.g.
```
docker run --rm -v $(pwd):/input_folder fkiecad/cwe_checker /input_folder/binary --bare-metal-config /input_folder/bare_metal_config.json
```
Keep in mind that you have to adjust the contents of the bare-metal configuration JSON to the MCU that the binary is running on!

Regarding 2: No, `.hex` files are not supported. If the hex file is just the contents of a binary represented as hex numbers, you could translate it to the binary it represents and then feed the binary to the cwe_checker instead.

**Comment by firmianay** [comment]
thanks!
