### ISSUE TITLE
Getting error while trying to run cwe_checker

### ISSUE THREAD

**Issue by soma345** [fkie-cad/cwe_checker#261]
could you please let me know what will be the actual command . I have tried with below but I am getting error . 

my firmware bin file in this path = ~/Desktop/MobileProject   My bin file name _demo_4.9.8.501.bin.extracted 

sudo docker run --rm -v ~/Desktop/MobileProject:/input fkiecad/cwe_checker /input                                                                                                  126 ⨯
[sudo] password for kali: 
error: Invalid value for '<binary>': /input is not a file.

Even trying to install locally 
cwe_checker BINARY - Not working 

Request your help

**Comment by Enkelmann** [comment]
If I am reading your Docker command correctly, then you provide a folder as input to the cwe_checker. But you have to provide a binary file as input, since the cwe_checker only analyzes single binaries. The cwe_checker also cannot analyze a whole firmware (containing many binaries), you would have to analyze one binary at a time from the firmware.

**Comment by soma345** [comment]
Hello ,

Thank you for your response.
Then could you help me to run the command . If I want to run this command
for firmware . Then how will I approach with this tool.


Thanks
Soma

**Comment by Enkelmann** [comment]
I recommend [FACT](https://github.com/fkie-cad/FACT_core) for the purpose of analyzing complete firmware images. It also has a cwe_checker plugin that runs the cwe_checker on every binary inside the firmware for you.

**Comment by soma345** [comment]
I also tried with Gidhra . I am getting error. This is also not running for individual file . 



 File "/usr/share/ghidra/Ghidra/Features/Python/data/jython-2.7.1/Lib/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
cwe_checker_ghidra_plugin.py> Finished!
cwe_checker_ghidra_plugin.py> Running...
Traceback (most recent call last):
  File "/home/kali/ghidra_scripts/cwe_checker_ghidra_plugin.py", line 63, in <module>
    main()
  File "/home/kali/ghidra_scripts/cwe_checker_ghidra_plugin.py", line 50, in main
    warnings = get_cwe_checker_output()
  File "/home/kali/ghidra_scripts/cwe_checker_ghidra_plugin.py", line 42, in get_cwe_checker_output
    return json.load(json_file)
  File "/usr/share/ghidra/Ghidra/Features/Python/data/jython-2.7.1/Lib/json/__init__.py", line 286, in load
    return loads(fp.read(),
  File "/usr/share/ghidra/Ghidra/Features/Python/data/jython-2.7.1/Lib/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/share/ghidra/Ghidra/Features/Python/data/jython-2.7.1/Lib/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/share/ghidra/Ghidra/Features/Python/data/jython-2.7.1/Lib/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
cwe_checker_ghidra_plugin.py> Finished!

**Comment by soma345** [comment]
For FACT tools , it is mentioned that $ ./start_all_installed_fact_components  file contains all the command but this file is not in the install folder . Could you help me to find that file .

**Comment by Enkelmann** [comment]
The Ghidra error is unfamiliar to me. Can you share the binary file where the error occured?

If you followed the FACT installation instructions, it should be in the FACT install folder. But please ask FACT-related questions in the FACT repository, not here. Or use their [Gitter channel](https://gitter.im/FACT_core/community) for quick advice.

**Comment by Enkelmann** [comment]
Since this thread is rather old and I cannot debug the Ghidra-related error without more information from the issue creator I am closing this issue for now. Feel free to reopen the issue if the problem persists in newer cwe_checker versions and if you can provide some more information on the binary in question to help me debug it.
