### ISSUE TITLE
Fixpoint computation doesn't use default node values internally

### ISSUE THREAD

**Issue by JamesShaker** [fkie-cad/cwe_checker#272]
Apologies if I'm misunderstanding the intended behaviour of default nodes in fixed point computations, but it seems they're not being fully utilised.

Whilst `get_node_value` ([here](https://github.com/fkie-cad/cwe_checker/blob/9981d74696222374d374f93b25d117fb22c3206e/src/cwe_checker_lib/src/analysis/fixpoint.rs#L171) on line 171 of `src/cwe_checker_lib/src/analysis/fixpoint.rs`) correctly returns the `default_value` when a node has no specified value, the `update_edge` function does not refer to it but instead directly looks to the `node_values`, ignoring the update if no value is specified. ([here](https://github.com/fkie-cad/cwe_checker/blob/9981d74696222374d374f93b25d117fb22c3206e/src/cwe_checker_lib/src/analysis/fixpoint.rs#L204) on line 204 of `src/cwe_checker_lib/src/analysis/fixpoint.rs`)

Thus the `default_value` is used when communicating the results of nodes for which no value has been calculated externally, but not when calculating the results of nodes that have no value yet internally. Is this intended?

**Comment by Enkelmann** [comment]
I think you found a bug here! If I remember correctly, no analysis makes use of default values for nodes yet, so I will have to write a test analysis to make sure. But in theory default values should be used like any other node value when computing the fixpoint, which would mean that the `update_edge` function must also use it if a default value exists. I will investigate this.
