### ISSUE TITLE
opam install cwe_checker error

### ISSUE THREAD

**Issue by sucof** [fkie-cad/cwe_checker#29]
when I want to install cwe_checker using opam install cwe_checker , it display:[ERROR] No package named cwe_checker found, why?

**Comment by jstucke** [comment]
First, check that you have the right opam version. `cwe_checker` needs at least version 2. 
Second, run `opam update` to fetch the newest package information. Then it should be able to find the package.

**Comment by sucof** [comment]
Thanks, it's work.
