### ISSUE TITLE
What is the meaning of nodes' weight&next and edges' weight&next&node?Can you describe the graph in detail?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#299]
![image-20220321203031712](https://shmily8421.oss-cn-beijing.aliyuncs.com//image/image-20220321203031712.png)

![image-20220321203046934](https://shmily8421.oss-cn-beijing.aliyuncs.com//image/image-20220321203046934.png)

**Comment by Enkelmann** [comment]
Hmm, this looks like some internal representation of the graph data structure, but not one meant for being read by humans. The weight that you printed is probably just a pointer to the data structure that contains the actual node weight.

For understanding the structure of the control flow graph as generated by the cwe_checker, I recommend reading the documentation comments in `src/cwe_checker_lib/src/analysis/graph.rs`, which describes the graph. It also contains the `Node` and `Edge` structs that represent the actual nodes and edges of the control flow graph (although they are implemented as node weights and edge weights to be precise). The documentation comments for both structs should also be of interest to you. If you still have questions after reading those doc comments, ask your questions here. :-)

**Comment by Enkelmann** [comment]
I am closing the issue for now. But feel free to still ask questions here and reopen the issue if you want!
