### ISSUE TITLE
Why a certain block is both start and end?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#304]
![image](https://user-images.githubusercontent.com/62237611/159607006-36c99286-d3ac-4070-a351-58240f21b021.png)
I can't understand the struct of graph.

**Comment by Enkelmann** [comment]
Every basic block gets two *different* nodes in the control flow graph. One denoting the point in time where the execution of the block starts and one denoting the point in time where the execution of the block ends. The two nodes are connected by an edge denoting the time frame of the execution of the block.

**Comment by Shmily8421** [comment]
So a function will be treated one block, two nodes. The graph depicts the jump relationship of these nodes, that is the control flow graph?

**Comment by Enkelmann** [comment]
One function consists of many basic blocks. But yes, the graph depicts the control flow or as you put it jump relationships between those node.

**Comment by Shmily8421** [comment]
What logic do you use to split one function into several blocks?

**Comment by Enkelmann** [comment]
If you are unfamiliar with the notion of basic blocks in the context of control flow graphs you may want to read up on that topic first. This is assumed prior knowledge and not explained anywhere in the cwe_checker.

We mainly use Ghidra for splitting up functions into basic blocks.
