### ISSUE TITLE
Why the graph needed to reverse?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#306]
![image](https://user-images.githubusercontent.com/62237611/160037142-14bd70ec-fb2f-47ad-8640-74fd3d7743a2.png)

**Comment by Enkelmann** [comment]
Depending on the analysis you may want to track the data flow in a program in the order of the control flow (e.g. you have some source of information and want to find out where it flows to) or in the reversed order (e.g. you have some point of interest and want to find out what information flows into this point). In the analysis you are looking at we track information in the reversed order.
