### ISSUE TITLE
thread 'main' panicked at 'not implemented'

### ISSUE THREAD

**Issue by anzosasuke** [fkie-cad/cwe_checker#307]
I was using it to analyze a C binary but it gave me this error. The cwe-checker is installed locally. 

thread 'main' panicked at 'not implemented', /home/a967a038/.cargo/registry/src/github.com-1ecc6299db9ec823/apint-0.2.0/src/apint/arithmetic.rs:350:17

What does this mean?
[bin.tar.gz](https://github.com/fkie-cad/cwe_checker/files/8347444/bin.tar.gz)

**Comment by Enkelmann** [comment]
This was an oversight by me. I missed to catch a special case of a division operation that is not supported by our dependency `apint`. I have already opened a pull request for the bugfix in #308 and will merge it later today if our CI approves it.

Thank you for providing an example binary! This made finding and fixing the problem very straightforward for me.

**Comment by Enkelmann** [comment]
Should be fixed now. Feel free to reopen the issue if you should stumble upon a variant of this bug that still leads to crashes.

**Comment by anzosasuke** [comment]
Thanks so much
