### ISSUE TITLE
arm elf file checker error

### ISSUE THREAD

**Issue by waytai** [fkie-cad/cwe_checker#327]
Execution of Ghidra plugin failed: Process was terminated.
ERROR REPORT: Import failed for file: /home/local/*.elf

**Comment by Enkelmann** [comment]
This looks like Ghidra was unable to open your binary. Have you tried opening it in the Ghidra GUI?

**Comment by Enkelmann** [comment]
Since there was no further response from the issue creator I am closing the issue.
