### ISSUE TITLE
Problem with start a docker container

### ISSUE THREAD

**Issue by dukebarman** [fkie-cad/cwe_checker#33]
When I try to run a docker image after build or run a container, every time have an error:

```
opam: opam: Missing argument.
      Usage: opam config [OPTION]... exec [--] COMMAND [ARG]...      
```

OS: Ubuntu 18.04

**Comment by Enkelmann** [comment]
Hm, my guess is that you try to run the image without providing any command line arguments like in  `docker run fkiecad/cwe_checker`, which does not work.

You can use the docker container like this:
```
docker run --rm -v [BINARY]:/tmp/input fkiecad/cwe_checker bap /tmp/input --pass=cwe-checker
```
This maps the file `[BINARY]` from the file system to the file `/tmp/input` inside the docker container and then executes `bap /tmp/input --pass=cwe-checker` in the container.

Just calling `docker run fkiecad/cwe_checker` does not work, as our docker image has just a preinstalled version of the *cwe_checker* in it, but no docker-specific interface.

**Comment by dukebarman** [comment]
Thanks, you're right. I tried this variant and like an interactive shell with mounting my folder

```
docker run -it -v `pwd`:/opt fkiecad/cwe_checker
```
