### ISSUE TITLE
Code Analysis on PcodeExtractor.java

### ISSUE THREAD

**Issue by DubcekUnderPineappleTree** [fkie-cad/cwe_checker#330]
Most respect to Mr. Enkelmann:
Excuse me,could you please tell me whether you have cwe_checker - master/SRC/ghidra p_code_extractor/PcodeExtractor.java code analysis documentation?If so,could you please release it to me?Thanks a million!

**Comment by Enkelmann** [comment]
All documentation that exists for the P-Code-Extractor code is contained as code comments in the code itself, i.e. you have to read the Java code. I also do not understand why you keep assuming that there exists more documentation outside of this repository. And for what purpose you need it.
