### ISSUE TITLE
The script for IDA doesn't work

### ISSUE THREAD

**Issue by dukebarman** [fkie-cad/cwe_checker#34]
Generated script has got only two strings:

```
import sark
import idaapi
```

I think after refactoring of logging the output hasn't got "WARN" string so `cwe_checker_to_ida.py` cannot normal generate an IDA annotate script.

**Comment by tbarabosch** [comment]
Oh yes, I am going to fix it ASAP.

**Comment by tbarabosch** [comment]
PR #35 should fix this issue

**Comment by dukebarman** [comment]
Yeap, it works. Thanks!

I think better to add info at readme that the IDA script for converting uses python3.

P.S. `Done. Now execute generated script ~/ida_script.py with IDAPython (alt+F9).` maybe `(alt+F7)`?

**Comment by tbarabosch** [comment]
Yes, @Enkelmann is going to update the documentation.
