### ISSUE TITLE
docker how to speficy --bare-metal-config 

### ISSUE THREAD

**Issue by ZeroXLN** [fkie-cad/cwe_checker#363]
I used cwe_checker in docker, when I test with the test_sample.bin, it shows the error:
![image](https://user-images.githubusercontent.com/58169480/205613520-2ecdf16b-ce47-4ad3-8ff4-02774d24f88e.png)

So I try to add the bare-metal-config option, but it failed,
![image](https://user-images.githubusercontent.com/58169480/205613724-1aed3944-f63b-4929-b697-dd8745ea4069.png)

Anyone can help? Thanks!

**Comment by Enkelmann** [comment]
You forgot to also mount the bare metal configuration file into the Docker container. The path you provided to the Docker container is in your host system, not in the file system of the container. That is why the cwe_checker cannot access it. One possible solution is to put the binary and the config file into the same folder and then mount that folder into the Docker container. E.g.:
```
docker run --rm -v /path/to/host/folder:/input fkiecad/cwe_checker /input/binary --bare-metal-config /input/config.json
```

**Comment by ZeroXLN** [comment]
> You forgot to also mount the bare metal configuration file into the Docker container. The path you provided to the Docker container is in your host system, not in the file system of the container. That is why the cwe_checker cannot access it. One possible solution is to put the binary and the config file into the same folder and then mount that folder into the Docker container. E.g.:
> 
> ```
> docker run --rm -v /path/to/host/folder:/input fkiecad/cwe_checker /input/binary --bare-metal-config /input/config.json
> ```

Thanks a lot! It works for me.
