### ISSUE TITLE
command line error

### ISSUE THREAD

**Issue by XingweiLin** [fkie-cad/cwe_checker#39]
Hi, all

I followed the [https://fkie-cad.github.io/cwe_checker/doc/html/cwe_checker/index.html#ToolIntegration](url) to integrate cwe-checker into ida pro. 
But the command line error confused me.

```
$ bap xxx.so --pass=cwe-checker --cwe-checker-json --cwe-checker-out=cwe_hits.json
cwe-checker: unknown option `--json'.
             unknown option `--out'.
Usage: cwe-checker [OPTION]...
Try `cwe-checker --help' for more information.
```

**Comment by XingweiLin** [comment]
I installed `cwe-checker` by `opam install cwe-checker`.
opam compiler version is `4.07.1`, `cwe-checker` version is 0.2.0

**Comment by Enkelmann** [comment]
Both the online documentation and the json-output-feature were added after version 0.2. So right now the documentation is only accurate for the master branch of the repository, version 0.2 has no json-output.

For now I recommend using the master branch. The docker container is built using the master branch, so use docker if you don't want to manually compile the cwe_checker.

Starting with version 0.3 we will keep the online documentation in sync with the latest stable release.

**Comment by XingweiLin** [comment]
I see.

Btw, Does the default `cwe-checker` contains the cwe-125, cwe-415, cwe-416, cwe-787 checkers which should be emulated? How can I enable those checkers?

Thank you!

**Comment by Enkelmann** [comment]
No, the default `cwe_checker` does not run these checks since emulation is too slow to enable them by default right now. You can run the emulation-based checks by running (from the root folder of the repository):
```bash
bap PATH_TO_BINARY --recipe=recipes/emulation
```
Try it out on very small binaries first. For larger binaries the emulation may not terminate in an acceptable time frame.

**Comment by XingweiLin** [comment]
Thank you!
