### ISSUE TITLE
cwe_checker docker -o option fails 

### ISSUE THREAD

**Issue by ZeroXLN** [fkie-cad/cwe_checker#393]
I want to output the result to file, but when I used the -o option, it failed like this:
![image](https://user-images.githubusercontent.com/58169480/221778818-55f0961f-bc43-459d-9e5f-5b0e44dd189c.png)

**Comment by ZeroXLN** [comment]
> `/root/cwe_checker/firm/test` is the folder containing the binary
![image](https://user-images.githubusercontent.com/58169480/221822243-bce1c4a7-f770-4d51-a047-f8095cdc9dc1.png)

**Comment by Enkelmann** [comment]
Have you checked whether Docker has write permissions for the folder?

**Comment by Enkelmann** [comment]
Closing, since the issue seems stale and I could not reproduce the issue back then.
