### ISSUE TITLE
Execution of Ghidra plugin failed

### ISSUE THREAD

**Issue by trangnt2304** [fkie-cad/cwe_checker#400]
I tried to follow the usage step but it give me this error "Execution of Ghidra plugin failed. Use the --verbose flag to print Ghidra output for troubleshooting."

Can you check it for me? Thank you

![image](https://user-images.githubusercontent.com/105774467/226239383-2a94bb26-c97a-4f12-a1d5-a07f67ca8ecf.png)
![image](https://user-images.githubusercontent.com/105774467/226239389-ac183ab3-a688-4e6e-8d51-361018da63dd.png)

**Comment by Enkelmann** [comment]
I think you forgot to provide the `--bare-metal-config <config_file>` command line option. For bare-metal binaries we need to provide it, because Ghidra cannot guess things like the processor architecture for us.

**Comment by trangnt2304** [comment]
I use the test_sample.bin file so I dont know why it doesn't work. And the  <config_file>: Do you mean the path to the stm32f407vg.json file ?
![Screen Shot 2023-03-20 at 13 20 57](https://user-images.githubusercontent.com/105774467/226262228-94287320-12a4-402f-8d02-a8f61a9cc5b5.png)

![Screen Shot 2023-03-20 at 13 20 18](https://user-images.githubusercontent.com/105774467/226262132-279470b3-507c-437f-b342-e6e1eca8c5bd.png)

**Comment by Enkelmann** [comment]
> And the <config_file>: Do you mean the path to the stm32f407vg.json file ?

Yes, I mean exactly that one.

The `test_sample.bin` file you used is the one we use to check the functionality for bare-metal analyses. If you want to try out the ELF and PE test binaries used in our CI pipeline, you need to compile them first, as only their source code is part of the repository.

**Comment by trangnt2304** [comment]
![image](https://user-images.githubusercontent.com/105774467/226501298-e34f4ddf-9833-43c6-9658-628b5941fbdb.png)
 Invalid value "C:/Users/Admin/Downloads/CWE_ex/stm32f407vg.json" for '--bare-metal-config <BARE_METAL_CONFIG>': No such file or directory (os error 2)

**Comment by trangnt2304** [comment]
It gives me this error :(

**Comment by Enkelmann** [comment]
Because you need to mount the config file into the Docker container, the same as you did with the `test_sample.bin` binary. The Docker container cannot access files in your file system unless you mount them into the container first.

**Comment by trangnt2304** [comment]
![image](https://user-images.githubusercontent.com/105774467/226783304-f909f5c9-4fa7-45ff-aff2-813104d36234.png)
Hi, can you help me, I tried to run the image to create a container but it gives me this error

**Comment by Enkelmann** [comment]
The entry point of the Docker image is the cwe_checker, which expects a binary as argument. If you want to open a shell inside the Docker container, instead of directly running the cwe_checker, please look at general tutorials about Docker on how to do that.

I am closing this issue for now, since the topic seems to be general Docker usage support instead of cwe_checker support.
