### ISSUE TITLE
BAP 2.0 migration

### ISSUE THREAD

**Issue by XVilka** [fkie-cad/cwe_checker#41]
Since the BAP 2.0 release [is imminent](https://github.com/BinaryAnalysisPlatform/bap/releases/tag/v2.0.0), it would be awesome to port the cwe_checker too.

**Comment by Enkelmann** [comment]
Our plan right now is to publish version 0.3 of the cwe_checker very soon, but still depending on BAP 1.6. After that we will switch to BAP 2.0 on the master branch. This way we will have ample time to incorporate the new features into our code base the right way.

**Comment by Enkelmann** [comment]
The master branch is now on BAP 2.0.
