### ISSUE TITLE
Windows failed to compile

### ISSUE THREAD

**Issue by enomothem** [fkie-cad/cwe_checker#419]
```
error[E0432]: unresolved imports `nix::sys`, `nix::unistd`
 --> src\cwe_checker_lib\src\utils\ghidra.rs:8:11
  |
8 | use nix::{sys::stat, unistd};
  |           ^^^        ^^^^^^ no `unistd` in the root
  |           |
  |           could not find `sys` in `nix`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `cwe_checker_lib` (lib) due to previous error
```

**Comment by Enkelmann** [comment]
Yes, we currently use some Linux-specific code for communication with Ghidra in the cwe_checker that does not compile on Windows. But you can still use the cwe_checker on Windows by either using the Windows subsystem for Linux (WSL) or by using the prebuilt Docker images that we provide.

I can also offer help if someone wants to implement native Windows support (which should not be difficult).
