### ISSUE TITLE
cwe_checker docker container hang on

### ISSUE THREAD

**Issue by ZeroXLN** [fkie-cad/cwe_checker#421]
I use the docker container to analyze an ELF file. I use this command to limit its memory usage to avoid huge memory costs.
`docker run --name cwe --memory=6g --oom-kill-disable --rm -v /test:/input cwe_checker:stable -q /input/gosec`

Meanwhile, I use `top` command to check it's status, I saw it hangs on cwe_checker command, can the process status in top shows D(which means Disk sleep), how can  I solve it and get the analyze result ?

Here is the `top` output:
```
top - 21:58:25 up 31 min,  6 users,  load average: 13.67, 13.46, 11.51
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s): 33.2 us, 15.4 sy,  0.1 ni, 31.8 id, 19.4 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15749.7 total,    296.3 free,  12313.6 used,   3139.7 buff/cache
MiB Swap:  16332.0 total,   9486.0 free,   6846.0 used.   2851.6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                               
28740 operator  20   0 9555852   5.8g    240 D   3.7  37.6   1:20.92 cwe_checker 
```

Can anyone help me? Thanks a lot!

**Comment by ZeroXLN** [comment]
> I use the docker container to analyze an ELF file. I use this command to limit its memory usage to avoid huge memory costs. `docker run --name cwe --memory=6g --oom-kill-disable --rm -v /test:/input cwe_checker:stable -q /input/gosec`
> 
> Meanwhile, I use `top` command to check it's status, I saw it hangs on cwe_checker command, can the process status in top shows D(which means Disk sleep), how can I solve it and get the analyze result ?
> 
> Here is the `top` output: `top - 21:58:25 up 31 min, 6 users, load average: 13.67, 13.46, 11.51 Tasks: 1 total, 0 running, 1 sleeping, 0 stopped, 0 zombie %Cpu(s): 33.2 us, 15.4 sy, 0.1 ni, 31.8 id, 19.4 wa, 0.0 hi, 0.0 si, 0.0 st MiB Mem : 15749.7 total, 296.3 free, 12313.6 used, 3139.7 buff/cache MiB Swap: 16332.0 total, 9486.0 free, 6846.0 used. 2851.6 avail Mem
> 
> PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND 28740 operator 20 0 9555852 5.8g 240 D 3.7 37.6 1:20.92 cwe_checker `
> 
> Can anyone help me? Thanks a lot!

Image cannot upload because Github error, sorry

**Comment by ZeroXLN** [comment]
> I use the docker container to analyze an ELF file. I use this command to limit its memory usage to avoid huge memory costs. `docker run --name cwe --memory=6g --oom-kill-disable --rm -v /test:/input cwe_checker:stable -q /input/gosec`
> 
> Meanwhile, I use `top` command to check it's status, I saw it hangs on cwe_checker command, can the process status in top shows D(which means Disk sleep), how can I solve it and get the analyze result ?
> 
> Here is the `top` output:
> 
> ```
> top - 21:58:25 up 31 min,  6 users,  load average: 13.67, 13.46, 11.51
> Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
> %Cpu(s): 33.2 us, 15.4 sy,  0.1 ni, 31.8 id, 19.4 wa,  0.0 hi,  0.0 si,  0.0 st
> MiB Mem :  15749.7 total,    296.3 free,  12313.6 used,   3139.7 buff/cache
> MiB Swap:  16332.0 total,   9486.0 free,   6846.0 used.   2851.6 avail Mem 
> 
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                               
> 28740 operator  20   0 9555852   5.8g    240 D   3.7  37.6   1:20.92 cwe_checker 
> ```
> 
> Can anyone help me? Thanks a lot!

It turns 'R' (Running) status right now . but I've been waiting for a while, but I still haven't seen the analysis results.
```
top - 22:03:13 up 36 min,  6 users,  load average: 13.65, 13.39, 12.04
Tasks:   1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie
%Cpu(s): 31.7 us, 47.6 sy,  0.3 ni, 18.7 id,  1.8 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15749.7 total,    357.2 free,  12223.9 used,   3168.6 buff/cache
MiB Swap:  16332.0 total,   7647.2 free,   8684.8 used.   2941.7 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                               
28740 operator  20   0   12.0g   5.9g      0 R  74.1  38.1   2:11.33 cwe_checker   
```

**Comment by Enkelmann** [comment]
The first thing that the cwe_checker does is executing Ghidra to disassemble the binary. This happens in a separate process, while the cwe_checker waits on Ghidra to write its results to a pipe. This waiting phase is probably what you can see in `top` as "disk sleep". When the status switches to "R" in `top`, then Ghidra finished disassembling and the cwe_checker starts its own analysis.

Since the disassembly with Ghidra apparently already took some time for your binary, I would assume that the binary in question is somewhat larger. The cwe_checker is still not optimized to handle large binaries and they can lead to excessive runtime or memory usage. If your binary is not that large, the culprit could also be a bug in the cwe_checker. Especially if the binary is around 1MB or less I would love to take a look at it to find out if I can identify any cwe_checker bugs.

Oh, one last thing: Searching for `gosec` yields a project written in Go as the first result. I have not tried out the cwe_checker for programs written in other languages than C and C++. There is a significant chance that the cwe_checker will not be able to handle Go binaries out of the box, i.e. will not return any meaningful results! Just so that you are aware.

**Comment by ZeroXLN** [comment]
> The first thing that the cwe_checker does is executing Ghidra to disassemble the binary. This happens in a separate process, while the cwe_checker waits on Ghidra to write its results to a pipe. This waiting phase is probably what you can see in `top` as "disk sleep". When the status switches to "R" in `top`, then Ghidra finished disassembling and the cwe_checker starts its own analysis.
> 
> Since the disassembly with Ghidra apparently already took some time for your binary, I would assume that the binary in question is somewhat larger. The cwe_checker is still not optimized to handle large binaries and they can lead to excessive runtime or memory usage. If your binary is not that large, the culprit could also be a bug in the cwe_checker. Especially if the binary is around 1MB or less I would love to take a look at it to find out if I can identify any cwe_checker bugs.
> 
> Oh, one last thing: Searching for `gosec` yields a project written in Go as the first result. I have not tried out the cwe_checker for programs written in other languages than C and C++. There is a significant chance that the cwe_checker will not be able to handle Go binaries out of the box, i.e. will not return any meaningful results! Just so that you are aware.

Okay， Got it.
Thanks a lot
