### ISSUE TITLE
Add Cutter/Rizin/Radare2 plugins

### ISSUE THREAD

**Issue by XVilka** [fkie-cad/cwe_checker#45]
I noticed you have a plugin for Ghidra, but it is not the only one FOSS tool available.
[Rizin](https://github.com/rizinorg/rizin) is a highly-portable cross-platform reverse engineering framework and a toolkit without dependencies.  It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `rz-pm`), and integration with various decompilers. For example, ghidra decompiler plugin - [rz-ghidra](https://github.com/rizinorg/rz-ghidra). It is actively developed and can be easily integrated in various open source and commercial products.

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For documentation on writing plugins for rizin see [Scripting](https://book.rizin.re/scripting/intro.html) and [Plugins](https://book.rizin.re/plugins/intro.html) Rizin Book chapters.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to rizin:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/rizinorg/cutter-plugins) of various popular plugins.

**Comment by Enkelmann** [comment]
Yes, a plugin for Radare2 would be nice. Since we already support json output, a plugin should be easy enough to implement and contributions are always welcome. :-)

Unfortunately, this isn't a high priority task for us right now, so it may take some time until we find the time to work on this ourselves.

**Comment by Enkelmann** [comment]
Closing the issue for now. Because of the limited developer resources available right now we will not be able to offer support for any plugin beyond the Ghidra plugin for the time being.
