### ISSUE TITLE
Unclear instructions on how to run with Ida 

### ISSUE THREAD

**Issue by paramikoooo** [fkie-cad/cwe_checker#56]
When I download the last release version , How do I run it with ida pro?
I read README.md but still not understand
I tried to run cwe_checker/CweCheckerParser.py , but Ida Pro 7.4 did not give me any results

**Comment by Enkelmann** [comment]
The script only imports the already generated cwe_checker results into IDA Pro, so you have to run the cwe_checker first. How to run the cwe_checker and how to use the script to import the results to IDA Pro is explained in the online documentation [here](https://fkie-cad.github.io/cwe_checker/doc/html/cwe_checker/index.html). If it is still unclear after reading the instructions there, please tell me!

I will leave the issue open until we updated the readme. We need to overhaul it anyway.

**Comment by XVilka** [comment]
I have a suggestion how loading and running these scripts can be autotested. There exist a project [python-idb](https://github.com/williballenthin/python-idb) that allows to open IDB files without IDA Pro itself, and some basic IDAPython-like subset of the API. Depending on the functions used it might be useful for this purpose.

See also https://github.com/BinaryAnalysisPlatform/bap/issues/859

**Comment by Enkelmann** [comment]
Closing the issue, since it is outdated. The up-to-date issue for this topic is issue #217.
