### ISSUE TITLE
Migrate Taint engine to Primus Taint

### ISSUE THREAD

**Issue by XVilka** [fkie-cad/cwe_checker#72]
Currently there is some basic code in cwe_checker, but it doesn't use Primus taint tracking features. See, for example:
- [BAP/plugins/primus_taint](https://github.com/BinaryAnalysisPlatform/bap/tree/master/plugins/primus_taint)
- [BAP/plugins/primus_propagate_taint](https://github.com/BinaryAnalysisPlatform/bap/tree/master/plugins/primus_propagate_taint)

I see that [checkers/cwe_476.ml](https://github.com/fkie-cad/cwe_checker/blob/master/src/checkers/cwe_476.ml) has some code for working with tainting but it's one checker-specific and too basic. My suggestion is:
- Use Primus Taint plugins
- Make an abstract taint interface that would be available for all checker authors.

**Comment by Enkelmann** [comment]
Primus taint tracking is based on symbolic execution. The taint tracking in cwe_476 is based on data-flow analysis. Furthermore, we made a deliberate choice to concentrate on data-flow analysis and *not* use symbolic execution for any checks for the time being.

There will be an abstract tainting interface for checks to use at some point. I am working on the foundation for it and more general data-flow based checks right now. However, it is far from finished. And as soon as it is finished, we will also need some time to experiment with it before we commit to a stable interface for other authors to use. So you have to be patient, it will take a while until you can use it.

**Comment by ivg** [comment]
> Primus taint tracking is based on symbolic execution.

Just to clarify, Primus Taint tracking is not (by default) based on the symbolic execution mode (though [it is possible][1] to devise one). It uses microexecution underneath the hood to derive data-flow facts. It is much less precise but has much higher coverage than the symbolic execution mode.

[1]: https://github.com/BinaryAnalysisPlatform/bap/wiki/Tutorial:-writing-a-symbolic-taint-analyzer
