### ISSUE TITLE
Assessment does not end

### ISSUE THREAD

**Issue by aug2uag** [fkie-cad/cwe_checker#81]
Hello! I'm running an assessment on a binary named "Banload" on a Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz 16GB RAM VirtualBox VM:

5MB `e5cb86789b8770b8c2fa35f67bbd48b4cd305217f8bb05d37aa437718c076042` binary at https://github.com/InQuest/malware-samples/tree/master/2019-05-Banload

The command I used was:
`cwe_checker /tmp/input/e5cb86789b8770b8c2fa35f67bbd48b4cd305217f8bb05d37aa437718c076042`

The assessment does not end, it's been running for a few days, and the assessment does not slow down or hang, only continues.

Could not find a means for detecting "when" the assessment may be given up, and stopped. I was curious if you came by such a condition before and/or how you would handle it.

**Comment by Enkelmann** [comment]
Right now, neither the *cwe_checker* itself nor BAP, the tool on which it is built upon, are optimized for resource-constrained environments. This results in rather huge amounts of RAM needed for analyzing bigger binaries. A non-finishing assessment in your case probably means that BAP ran out of RAM to use, I experienced similar behavior when running out of RAM with BAP.

From my experience binaries larger than 10MB (stripped) usually cannot be analyzed even on a machine with 64GB RAM. As a rule of thumb, if the analysis runs for more than an hour, there is a good chance it will never finish, even if it doesn't run out of RAM. Unfortunately, there is no trick to solve this yet, we simply cannot analyze binaries where this happens at the moment.

There is another caveat that I need to mention: The *cwe_checker* is not meant for analyzing malware samples. It is meant for finding possible bugs in benign software and to that end assumes reasonably benign coding practices. In particular, any kind of nontrivial code obfuscation will probably render the analysis useless. The results also only point out places of possible bugs, they don't help you in understanding what a binary actually does (which is usually the goal in malware analysis).

**Comment by aug2uag** [comment]
Very well. Thanks for your response!
